(let ((count 0))
  (defun getcount ()
    (setq count (+ count 1))
    count)
  (let ((count 10))
     (print (getcount))
     (print (getcount))
     (print (getcount))
     (assert (= 4 (print (getcount))))
	 ))
