(defun itemCheck (tree)
 (if (= (length tree) 1)
  (car tree)
  (+ (car tree) (- (itemCheck (car (cdr tree))) (itemCheck (car (cdr (cdr tree))))))
 ))
(defun bottomUpTree (item depth)
 (if (= depth 0)
  (list item)
  (list item (bottomUpTree (- (* item 2) 1) (- depth 1)) (bottomUpTree (* item 2) (- depth 1)))
 ))
(itemCheck (bottomUpTree 0 14))
